package interfaces;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import interfaces.views.*;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import logica.Gestion;
/**
 *
 * @author Conecta
 */
public class PanelPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PanelPrincipal
     */
    private Gestion gestion;
    
    public PanelPrincipal(Gestion gestion) {
        this.gestion = gestion;
        initComponents();

        // Añadir el action listener manualmente
        inscripcionCarrera.addActionListener((java.awt.event.ActionEvent evt) -> {
            inscripcionCarreraPerformed(evt);
        });

        inscripcionMateria.addActionListener((java.awt.event.ActionEvent evt) -> {
            inscripcionMateriaPerformed(evt);
        });
        
        verificar.addActionListener((java.awt.event.ActionEvent evt) -> {
            verificarPerformed(evt);
        });
        
        contenidoInicial();
    }

    private void contenidoInicial(){
        mostrarPanel(new PanelInicio());
    }
    
    public void mostrarPanel(JPanel p){
        p.setSize(1000, 600);
        p.setLocation(0,0);
        
        contenidoCambiante.removeAll();
        contenidoCambiante.add(p, BorderLayout.CENTER);
        contenidoCambiante.revalidate();
        contenidoCambiante.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        panelOpciones = new javax.swing.JPanel();
        gestionTitulo = new javax.swing.JLabel();
        separadorDelTitulo = new javax.swing.JSeparator();
        inicio = new javax.swing.JButton();
        altaAlumno = new javax.swing.JButton();
        altaCarrera = new javax.swing.JButton();
        altaPlanEstu = new javax.swing.JButton();
        inscripcionCarrera = new javax.swing.JButton();
        inscripcionMateria = new javax.swing.JButton();
        alumnos = new javax.swing.JButton();
        altaNotas = new javax.swing.JButton();
        materias = new javax.swing.JButton();
        carreras = new javax.swing.JButton();
        verificar = new javax.swing.JButton();
        contenidoCambiante = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setMinimumSize(new java.awt.Dimension(1000, 600));
        fondo.setPreferredSize(new java.awt.Dimension(1000, 600));

        panelOpciones.setBackground(new java.awt.Color(255, 133, 161));
        panelOpciones.setMinimumSize(new java.awt.Dimension(350, 600));
        panelOpciones.setPreferredSize(new java.awt.Dimension(350, 600));

        gestionTitulo.setBackground(new java.awt.Color(255, 255, 255));
        gestionTitulo.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        gestionTitulo.setForeground(new java.awt.Color(255, 255, 255));
        gestionTitulo.setText("GESTION ACADEMICA");

        separadorDelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        separadorDelTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        inicio.setBackground(new java.awt.Color(255, 10, 84));
        inicio.setFont(new java.awt.Font("Century Gothic", 3, 15)); // NOI18N
        inicio.setForeground(new java.awt.Color(255, 255, 255));
        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/04.png"))); // NOI18N
        inicio.setText("INICIO");
        inicio.setIconTextGap(10);
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        altaAlumno.setBackground(new java.awt.Color(255, 10, 84));
        altaAlumno.setFont(new java.awt.Font("Century Gothic", 3, 15)); // NOI18N
        altaAlumno.setForeground(new java.awt.Color(255, 255, 255));
        altaAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/03.png"))); // NOI18N
        altaAlumno.setText("Alta de Alumno");
        altaAlumno.setIconTextGap(10);
        altaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaAlumnoActionPerformed(evt);
            }
        });

        altaCarrera.setBackground(new java.awt.Color(255, 10, 84));
        altaCarrera.setFont(new java.awt.Font("Century Gothic", 3, 15)); // NOI18N
        altaCarrera.setForeground(new java.awt.Color(255, 255, 255));
        altaCarrera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/03.png"))); // NOI18N
        altaCarrera.setText("Alta de Carrera");
        altaCarrera.setIconTextGap(10);
        altaCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaCarreraActionPerformed(evt);
            }
        });

        altaPlanEstu.setBackground(new java.awt.Color(255, 10, 84));
        altaPlanEstu.setFont(new java.awt.Font("Century Gothic", 3, 15)); // NOI18N
        altaPlanEstu.setForeground(new java.awt.Color(255, 255, 255));
        altaPlanEstu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/03.png"))); // NOI18N
        altaPlanEstu.setText("Alta de Plan de Estudios");
        altaPlanEstu.setIconTextGap(10);
        altaPlanEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaPlanEstuActionPerformed(evt);
            }
        });

        inscripcionCarrera.setBackground(new java.awt.Color(255, 10, 84));
        inscripcionCarrera.setFont(new java.awt.Font("Century Gothic", 3, 15)); // NOI18N
        inscripcionCarrera.setForeground(new java.awt.Color(255, 255, 255));
        inscripcionCarrera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/02.png"))); // NOI18N
        inscripcionCarrera.setText("Inscripcion a Carrera");
        inscripcionCarrera.setIconTextGap(10);

        inscripcionMateria.setBackground(new java.awt.Color(255, 10, 84));
        inscripcionMateria.setFont(new java.awt.Font("Century Gothic", 3, 15)); // NOI18N
        inscripcionMateria.setForeground(new java.awt.Color(255, 255, 255));
        inscripcionMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/02.png"))); // NOI18N
        inscripcionMateria.setText("Inscripcion a Materia");
        inscripcionMateria.setIconTextGap(10);

        alumnos.setBackground(new java.awt.Color(255, 10, 84));
        alumnos.setFont(new java.awt.Font("Century Gothic", 3, 15)); // NOI18N
        alumnos.setForeground(new java.awt.Color(255, 255, 255));
        alumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/01.png"))); // NOI18N
        alumnos.setText("Alumnos");
        alumnos.setIconTextGap(10);
        alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnosActionPerformed(evt);
            }
        });

        altaNotas.setBackground(new java.awt.Color(255, 10, 84));
        altaNotas.setFont(new java.awt.Font("Century Gothic", 3, 15)); // NOI18N
        altaNotas.setForeground(new java.awt.Color(255, 255, 255));
        altaNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/03.png"))); // NOI18N
        altaNotas.setText("Alta de Notas");
        altaNotas.setIconTextGap(10);

        materias.setBackground(new java.awt.Color(255, 10, 84));
        materias.setFont(new java.awt.Font("Century Gothic", 3, 15)); // NOI18N
        materias.setForeground(new java.awt.Color(255, 255, 255));
        materias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/02.png"))); // NOI18N
        materias.setText("Materias");
        materias.setIconTextGap(10);

        carreras.setBackground(new java.awt.Color(255, 10, 84));
        carreras.setFont(new java.awt.Font("Century Gothic", 3, 15)); // NOI18N
        carreras.setForeground(new java.awt.Color(255, 255, 255));
        carreras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/02.png"))); // NOI18N
        carreras.setText("Carreras");
        carreras.setIconTextGap(10);

        verificar.setBackground(new java.awt.Color(255, 10, 84));
        verificar.setFont(new java.awt.Font("Century Gothic", 3, 15)); // NOI18N
        verificar.setForeground(new java.awt.Color(255, 255, 255));
        verificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/02.png"))); // NOI18N
        verificar.setText("Verificar Termino de Carrera");
        verificar.setIconTextGap(10);

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(separadorDelTitulo)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inscripcionCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(materias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(altaNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inscripcionMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(altaPlanEstu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(altaCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(altaAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(gestionTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(gestionTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorDelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(altaAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(altaCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(altaPlanEstu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inscripcionCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inscripcionMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(altaNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(materias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );

        contenidoCambiante.setBackground(new java.awt.Color(255, 255, 255));
        contenidoCambiante.setMinimumSize(new java.awt.Dimension(644, 600));
        contenidoCambiante.setPreferredSize(new java.awt.Dimension(644, 600));
        contenidoCambiante.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout contenidoCambianteLayout = new javax.swing.GroupLayout(contenidoCambiante);
        contenidoCambiante.setLayout(contenidoCambianteLayout);
        contenidoCambianteLayout.setHorizontalGroup(
            contenidoCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        contenidoCambianteLayout.setVerticalGroup(
            contenidoCambianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(panelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenidoCambiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
            .addComponent(contenidoCambiante, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        mostrarPanel(new PanelInicio());
    }//GEN-LAST:event_inicioActionPerformed

    private void altaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaAlumnoActionPerformed
        mostrarPanel(new PanelAltaAlumno(gestion));
    }//GEN-LAST:event_altaAlumnoActionPerformed

    private void altaCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaCarreraActionPerformed
        mostrarPanel(new PanelAltaCarrera(gestion));
    }//GEN-LAST:event_altaCarreraActionPerformed

    private void altaPlanEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaPlanEstuActionPerformed
        mostrarPanel(new PanelAltaPlanDeEstudios(gestion));
    }//GEN-LAST:event_altaPlanEstuActionPerformed

    private void inscripcionCarreraPerformed(java.awt.event.ActionEvent evt){
        mostrarPanel(new PanelInscripcionCarrera(gestion));
    }
    
    private void inscripcionMateriaPerformed(java.awt.event.ActionEvent evt){
        mostrarPanel(new PanelInscripcionMateria(gestion));
    }
    
    private void verificarPerformed(java.awt.event.ActionEvent evt){
        mostrarPanel(new PanelVerificacion(gestion));
    }
    
    private void alumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alumnosActionPerformed

        /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaAlumno;
    private javax.swing.JButton altaCarrera;
    private javax.swing.JButton altaNotas;
    private javax.swing.JButton altaPlanEstu;
    private javax.swing.JButton alumnos;
    private javax.swing.JButton carreras;
    private javax.swing.JPanel contenidoCambiante;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel gestionTitulo;
    private javax.swing.JButton inicio;
    private javax.swing.JButton inscripcionCarrera;
    private javax.swing.JButton inscripcionMateria;
    private javax.swing.JButton materias;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JSeparator separadorDelTitulo;
    private javax.swing.JButton verificar;
    // End of variables declaration//GEN-END:variables
}
