/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.views;
import java.awt.HeadlessException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import logica.*;
/**
 *
 * @author Conecta
 */
public class PanelVerificacion extends javax.swing.JPanel {
private Gestion gestion;
    /**
     * Creates new form PanelInscripcionCarrera
     */
    public PanelVerificacion(Gestion gestion) {
        this.gestion = gestion;
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenidoVerificacion = new javax.swing.JPanel();
        tituloVerificacion = new javax.swing.JLabel();
        tituloSeleccionaAlumnoInscripcionMateria = new javax.swing.JLabel();
        seleccionarAlumnoBoxInscripcionMateria = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(644, 600));
        setPreferredSize(new java.awt.Dimension(644, 600));

        panelContenidoVerificacion.setBackground(new java.awt.Color(255, 255, 255));

        tituloVerificacion.setFont(new java.awt.Font("Century Gothic", 3, 28)); // NOI18N
        tituloVerificacion.setForeground(new java.awt.Color(164, 19, 60));
        tituloVerificacion.setText("Verificar Término de carrera del alumno:");

        tituloSeleccionaAlumnoInscripcionMateria.setBackground(new java.awt.Color(255, 255, 255));
        tituloSeleccionaAlumnoInscripcionMateria.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        tituloSeleccionaAlumnoInscripcionMateria.setForeground(new java.awt.Color(255, 77, 109));
        tituloSeleccionaAlumnoInscripcionMateria.setText("Seleccionar Alumno: ");

        seleccionarAlumnoBoxInscripcionMateria.setBackground(new java.awt.Color(255, 255, 255));
        seleccionarAlumnoBoxInscripcionMateria.setForeground(new java.awt.Color(0, 0, 0));
        seleccionarAlumnoBoxInscripcionMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        seleccionarAlumnoBoxInscripcionMateria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 10, 84), 2));
        seleccionarAlumnoBoxInscripcionMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarAlumnoBoxInscripcionMateriaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 10, 84));
        jButton1.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VERIFICAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContenidoVerificacionLayout = new javax.swing.GroupLayout(panelContenidoVerificacion);
        panelContenidoVerificacion.setLayout(panelContenidoVerificacionLayout);
        panelContenidoVerificacionLayout.setHorizontalGroup(
            panelContenidoVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoVerificacionLayout.createSequentialGroup()
                .addGroup(panelContenidoVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenidoVerificacionLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(panelContenidoVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloSeleccionaAlumnoInscripcionMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seleccionarAlumnoBoxInscripcionMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelContenidoVerificacionLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(tituloVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelContenidoVerificacionLayout.setVerticalGroup(
            panelContenidoVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoVerificacionLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(tituloVerificacion)
                .addGap(18, 18, 18)
                .addComponent(tituloSeleccionaAlumnoInscripcionMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccionarAlumnoBoxInscripcionMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(323, 323, 323))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenidoVerificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenidoVerificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void cargarDatos() {
        // Cargar alumnos
        DefaultComboBoxModel<String> modelAlumnos = new DefaultComboBoxModel<>();
        for (Alumno alumno : gestion.getListaDeAlumnos()) {
            modelAlumnos.addElement(alumno.getLegajo() + " - " + alumno.getNombre() + " " + alumno.getApellido());
        }
        seleccionarAlumnoBoxInscripcionMateria.setModel(modelAlumnos);
    }
    private void seleccionarAlumnoBoxInscripcionMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarAlumnoBoxInscripcionMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarAlumnoBoxInscripcionMateriaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (seleccionarAlumnoBoxInscripcionMateria.getSelectedIndex() == -1) {
            mostrarDialogoCentrado("Por favor, seleccione un alumno.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtener alumno seleccionado
        String alumnoSeleccionado = (String) seleccionarAlumnoBoxInscripcionMateria.getSelectedItem();

        // Extraer el legajo del alumno
        int legajo = Integer.parseInt(alumnoSeleccionado.split(" - ")[0]);

        try {
            // Verificar si el alumno terminó la carrera
            boolean terminoCarrera = gestion.verificarAlumnoTerminacionCarrera(legajo);

            if (terminoCarrera) {
                mostrarDialogoCentrado(
                    "El alumno ha completado todos los requisitos para finalizar la carrera.",
                    "Verificación Exitosa",
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                mostrarDialogoCentrado(
                    "El alumno aún no ha completado todos los requisitos para finalizar la carrera.",
                    "Verificación Completada",
                    JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            mostrarDialogoCentrado(
                "Error al verificar al alumno: " + e.getMessage(),
                "Error de Verificación",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Método para mostrar diálogos centrados en la pantalla y ajustados a la izquierda
    private void mostrarDialogoCentrado(String mensaje, String titulo, int tipoMensaje) {
        JOptionPane panel = new JOptionPane(mensaje, tipoMensaje);
        panel.setOptions(new Object[] {"OK"});
        JDialog dialogo = panel.createDialog(this, titulo);
        
        // Centrar el diálogo en la pantalla
        dialogo.setLocationRelativeTo(null);
        
        // Ajustar la posición hacia la izquierda
        java.awt.Point ubicacion = dialogo.getLocation();
        dialogo.setLocation(ubicacion.x - 80, ubicacion.y); // Ajustar 80 píxeles a la izquierda
        
        dialogo.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelContenidoVerificacion;
    private javax.swing.JComboBox<String> seleccionarAlumnoBoxInscripcionMateria;
    private javax.swing.JLabel tituloSeleccionaAlumnoInscripcionMateria;
    private javax.swing.JLabel tituloVerificacion;
    // End of variables declaration//GEN-END:variables
}
