/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.views;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import logica.Carrera;
import logica.Gestion;
import logica.Materia;
/**
 *
 * @author Conecta
 */
public class PanelAltaPlanDeEstudios extends javax.swing.JPanel {
private Gestion gestion;
    /**
     * Creates new form PanelAltaPlanDeEstudios
     */
    public PanelAltaPlanDeEstudios(Gestion gestion) {
        this.gestion = gestion;
        initComponents();
        configurarCampoTexto(codigoMateriaAltaPlanDeEstudios, "  Ingrese el código de la materia");
        configurarCampoTexto(nombreMateriaAltaPlanDeEstudios, "  Ingrese el nombre de la materia");
        configurarCampoTexto(numeroCuatriMateriaAltaPlanDeEstudios, "  Ingrese número de cuatrimestre de la materia");
        configurarCampoTexto(anioMateriaAltaPlanDeEstudios, "  Ingrese año de la materia");
        
                // Configurar el ComboBox de carreras
        actualizarComboBoxCarreras();
        
        // Configurar el ComboBox de correlativas
        actualizarComboBoxCorrelativas();
        
        // Agregar ActionListener al botón
        agregarMateriaBotonAltaPlanDeEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMateriaActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenidoAltaPlanDeEstudios = new javax.swing.JPanel();
        tituloPrincipalAltaPlanDeEstudios = new javax.swing.JLabel();
        tituloSeleccionaCarreraAltaPlanDeEstudios = new javax.swing.JLabel();
        seleccionarCarreraBoxAltaPlanDeEstudios = new javax.swing.JComboBox<>();
        tituloIngresarDatosMateriaAltaPlanDeEstudios = new javax.swing.JLabel();
        codigoMateriaAltaPlanDeEstudios = new javax.swing.JTextField();
        numeroCuatriMateriaAltaPlanDeEstudios = new javax.swing.JTextField();
        anioMateriaAltaPlanDeEstudios = new javax.swing.JTextField();
        obligatoriaCheckAltaPlanDeEstudios = new javax.swing.JCheckBox();
        optativaCheckAltaPlanDeEstudios = new javax.swing.JCheckBox();
        tituloSeleccionarCorrelativaAltaPlanDeEstudios = new javax.swing.JLabel();
        nombreMateriaAltaPlanDeEstudios = new javax.swing.JTextField();
        seleccionarCorrelativaBoxAltaPlanDeEstudios = new javax.swing.JComboBox<>();
        agregarMateriaBotonAltaPlanDeEstudios = new javax.swing.JToggleButton();

        setMinimumSize(new java.awt.Dimension(644, 600));
        setPreferredSize(new java.awt.Dimension(644, 600));

        panelContenidoAltaPlanDeEstudios.setBackground(new java.awt.Color(255, 255, 255));
        panelContenidoAltaPlanDeEstudios.setMinimumSize(new java.awt.Dimension(644, 600));

        tituloPrincipalAltaPlanDeEstudios.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        tituloPrincipalAltaPlanDeEstudios.setForeground(new java.awt.Color(164, 19, 60));
        tituloPrincipalAltaPlanDeEstudios.setText("CREAR PLAN DE ESTUDIOS");

        tituloSeleccionaCarreraAltaPlanDeEstudios.setBackground(new java.awt.Color(255, 255, 255));
        tituloSeleccionaCarreraAltaPlanDeEstudios.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        tituloSeleccionaCarreraAltaPlanDeEstudios.setForeground(new java.awt.Color(255, 77, 109));
        tituloSeleccionaCarreraAltaPlanDeEstudios.setText("Seleccionar carrera: ");

        seleccionarCarreraBoxAltaPlanDeEstudios.setBackground(new java.awt.Color(255, 255, 255));
        seleccionarCarreraBoxAltaPlanDeEstudios.setForeground(new java.awt.Color(0, 0, 0));
        seleccionarCarreraBoxAltaPlanDeEstudios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        seleccionarCarreraBoxAltaPlanDeEstudios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 10, 84), 2));
        seleccionarCarreraBoxAltaPlanDeEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarCarreraBoxAltaPlanDeEstudiosActionPerformed(evt);
            }
        });

        tituloIngresarDatosMateriaAltaPlanDeEstudios.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        tituloIngresarDatosMateriaAltaPlanDeEstudios.setForeground(new java.awt.Color(255, 77, 109));
        tituloIngresarDatosMateriaAltaPlanDeEstudios.setText("Ingresar datos de la materia:");

        codigoMateriaAltaPlanDeEstudios.setBackground(new java.awt.Color(255, 255, 255));
        codigoMateriaAltaPlanDeEstudios.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        codigoMateriaAltaPlanDeEstudios.setForeground(new java.awt.Color(102, 102, 102));
        codigoMateriaAltaPlanDeEstudios.setText("  Ingrese el código de la materia");
        codigoMateriaAltaPlanDeEstudios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 10, 84), 2, true));
        codigoMateriaAltaPlanDeEstudios.setPreferredSize(new java.awt.Dimension(700, 30));
        codigoMateriaAltaPlanDeEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoMateriaAltaPlanDeEstudiosActionPerformed(evt);
            }
        });

        numeroCuatriMateriaAltaPlanDeEstudios.setBackground(new java.awt.Color(255, 255, 255));
        numeroCuatriMateriaAltaPlanDeEstudios.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        numeroCuatriMateriaAltaPlanDeEstudios.setForeground(new java.awt.Color(102, 102, 102));
        numeroCuatriMateriaAltaPlanDeEstudios.setText("  Ingrese número de cuatrimestre de la materia");
        numeroCuatriMateriaAltaPlanDeEstudios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 10, 84), 2, true));
        numeroCuatriMateriaAltaPlanDeEstudios.setPreferredSize(new java.awt.Dimension(700, 30));
        numeroCuatriMateriaAltaPlanDeEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroCuatriMateriaAltaPlanDeEstudiosActionPerformed(evt);
            }
        });

        anioMateriaAltaPlanDeEstudios.setBackground(new java.awt.Color(255, 255, 255));
        anioMateriaAltaPlanDeEstudios.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        anioMateriaAltaPlanDeEstudios.setForeground(new java.awt.Color(102, 102, 102));
        anioMateriaAltaPlanDeEstudios.setText("  Ingrese año de la materia");
        anioMateriaAltaPlanDeEstudios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 10, 84), 2, true));
        anioMateriaAltaPlanDeEstudios.setPreferredSize(new java.awt.Dimension(700, 30));
        anioMateriaAltaPlanDeEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioMateriaAltaPlanDeEstudiosActionPerformed(evt);
            }
        });

        obligatoriaCheckAltaPlanDeEstudios.setBackground(new java.awt.Color(255, 255, 255));
        obligatoriaCheckAltaPlanDeEstudios.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        obligatoriaCheckAltaPlanDeEstudios.setForeground(new java.awt.Color(51, 51, 51));
        obligatoriaCheckAltaPlanDeEstudios.setText("Materia Obligatoria");
        obligatoriaCheckAltaPlanDeEstudios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 18, 31), 1, true));

        optativaCheckAltaPlanDeEstudios.setBackground(new java.awt.Color(255, 255, 255));
        optativaCheckAltaPlanDeEstudios.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        optativaCheckAltaPlanDeEstudios.setForeground(new java.awt.Color(51, 51, 51));
        optativaCheckAltaPlanDeEstudios.setText("Materia Optativa");

        tituloSeleccionarCorrelativaAltaPlanDeEstudios.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        tituloSeleccionarCorrelativaAltaPlanDeEstudios.setForeground(new java.awt.Color(255, 77, 109));
        tituloSeleccionarCorrelativaAltaPlanDeEstudios.setText("Seleccionar correlativa:");

        nombreMateriaAltaPlanDeEstudios.setBackground(new java.awt.Color(255, 255, 255));
        nombreMateriaAltaPlanDeEstudios.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        nombreMateriaAltaPlanDeEstudios.setForeground(new java.awt.Color(102, 102, 102));
        nombreMateriaAltaPlanDeEstudios.setText("  Ingrese el nombre de la materia");
        nombreMateriaAltaPlanDeEstudios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 10, 84), 2, true));
        nombreMateriaAltaPlanDeEstudios.setPreferredSize(new java.awt.Dimension(700, 30));
        nombreMateriaAltaPlanDeEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMateriaAltaPlanDeEstudiosActionPerformed(evt);
            }
        });

        seleccionarCorrelativaBoxAltaPlanDeEstudios.setBackground(new java.awt.Color(255, 255, 255));
        seleccionarCorrelativaBoxAltaPlanDeEstudios.setForeground(new java.awt.Color(0, 0, 0));
        seleccionarCorrelativaBoxAltaPlanDeEstudios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        seleccionarCorrelativaBoxAltaPlanDeEstudios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 10, 84), 2));
        seleccionarCorrelativaBoxAltaPlanDeEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarCorrelativaBoxAltaPlanDeEstudiosActionPerformed(evt);
            }
        });

        agregarMateriaBotonAltaPlanDeEstudios.setBackground(new java.awt.Color(255, 10, 84));
        agregarMateriaBotonAltaPlanDeEstudios.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        agregarMateriaBotonAltaPlanDeEstudios.setForeground(new java.awt.Color(255, 255, 255));
        agregarMateriaBotonAltaPlanDeEstudios.setText("AGREGAR MATERIA");

        javax.swing.GroupLayout panelContenidoAltaPlanDeEstudiosLayout = new javax.swing.GroupLayout(panelContenidoAltaPlanDeEstudios);
        panelContenidoAltaPlanDeEstudios.setLayout(panelContenidoAltaPlanDeEstudiosLayout);
        panelContenidoAltaPlanDeEstudiosLayout.setHorizontalGroup(
            panelContenidoAltaPlanDeEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoAltaPlanDeEstudiosLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panelContenidoAltaPlanDeEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloSeleccionaCarreraAltaPlanDeEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloPrincipalAltaPlanDeEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionarCarreraBoxAltaPlanDeEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloIngresarDatosMateriaAltaPlanDeEstudios)
                    .addComponent(obligatoriaCheckAltaPlanDeEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optativaCheckAltaPlanDeEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloSeleccionarCorrelativaAltaPlanDeEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionarCorrelativaBoxAltaPlanDeEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContenidoAltaPlanDeEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(codigoMateriaAltaPlanDeEstudios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(nombreMateriaAltaPlanDeEstudios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(numeroCuatriMateriaAltaPlanDeEstudios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(anioMateriaAltaPlanDeEstudios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(agregarMateriaBotonAltaPlanDeEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        panelContenidoAltaPlanDeEstudiosLayout.setVerticalGroup(
            panelContenidoAltaPlanDeEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoAltaPlanDeEstudiosLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(tituloPrincipalAltaPlanDeEstudios)
                .addGap(18, 18, 18)
                .addComponent(tituloSeleccionaCarreraAltaPlanDeEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionarCarreraBoxAltaPlanDeEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tituloIngresarDatosMateriaAltaPlanDeEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoMateriaAltaPlanDeEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreMateriaAltaPlanDeEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroCuatriMateriaAltaPlanDeEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anioMateriaAltaPlanDeEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(obligatoriaCheckAltaPlanDeEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optativaCheckAltaPlanDeEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloSeleccionarCorrelativaAltaPlanDeEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionarCorrelativaBoxAltaPlanDeEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarMateriaBotonAltaPlanDeEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenidoAltaPlanDeEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenidoAltaPlanDeEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void configurarCampoTexto(JTextField campo, String placeholder) {
       // Configurar el campo con el placeholder y color gris
       campo.setText(placeholder);
       campo.setForeground(Color.GRAY);

       // Aplicar un margen interno al campo de texto
       campo.setBorder(javax.swing.BorderFactory.createCompoundBorder(
           new javax.swing.border.LineBorder(new java.awt.Color(255, 10, 84), 2, true),
           javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0)));

       campo.addFocusListener(new FocusAdapter() {
           @Override
           public void focusGained(FocusEvent e) {
               if (campo.getText().equals(placeholder)) {
                   campo.setText("");
                   campo.setForeground(Color.BLACK);
               }
           }

           @Override
           public void focusLost(FocusEvent e) {
               if (campo.getText().isEmpty()) {
                   campo.setText(placeholder);
                   campo.setForeground(Color.GRAY);
               }
           }
       });
   }
    private void seleccionarCarreraBoxAltaPlanDeEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarCarreraBoxAltaPlanDeEstudiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarCarreraBoxAltaPlanDeEstudiosActionPerformed

    private void codigoMateriaAltaPlanDeEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoMateriaAltaPlanDeEstudiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoMateriaAltaPlanDeEstudiosActionPerformed

    private void numeroCuatriMateriaAltaPlanDeEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroCuatriMateriaAltaPlanDeEstudiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroCuatriMateriaAltaPlanDeEstudiosActionPerformed

    private void anioMateriaAltaPlanDeEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioMateriaAltaPlanDeEstudiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anioMateriaAltaPlanDeEstudiosActionPerformed

    private void nombreMateriaAltaPlanDeEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMateriaAltaPlanDeEstudiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMateriaAltaPlanDeEstudiosActionPerformed

    private void seleccionarCorrelativaBoxAltaPlanDeEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarCorrelativaBoxAltaPlanDeEstudiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarCorrelativaBoxAltaPlanDeEstudiosActionPerformed

    private void actualizarComboBoxCarreras() {
        seleccionarCarreraBoxAltaPlanDeEstudios.removeAllItems();
        for (Carrera carrera : gestion.getListaDeCarreras()) {
            seleccionarCarreraBoxAltaPlanDeEstudios.addItem(carrera.getNombreCarrera());
        }
    }
    
    private void actualizarComboBoxCorrelativas() {
        seleccionarCorrelativaBoxAltaPlanDeEstudios.removeAllItems();
        seleccionarCorrelativaBoxAltaPlanDeEstudios.addItem("Ninguna");
        String carreraSeleccionada = (String) seleccionarCarreraBoxAltaPlanDeEstudios.getSelectedItem();
        if (carreraSeleccionada != null) {
            for (Carrera carrera : gestion.getListaDeCarreras()) {
                if (carrera.getNombreCarrera().equals(carreraSeleccionada)) {
                    for (Materia materia : carrera.getPlanDeEstudio().getListaDeMaterias()) {
                        seleccionarCorrelativaBoxAltaPlanDeEstudios.addItem(materia.getCodigoMateria() + " - " + materia.getNombreMateria());
                    }
                }
            }
        }
    }
    
    private void agregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // Obtener los valores de los campos
            String codigoMateria = codigoMateriaAltaPlanDeEstudios.getText().trim();
            String nombreMateria = nombreMateriaAltaPlanDeEstudios.getText().trim();
            int numeroCuatrimestre;
            int anio;

            // Verificar si los campos son placeholders
            if (codigoMateria.equals("  Ingrese el código de la materia") || 
                nombreMateria.equals("  Ingrese el nombre de la materia") ||
                numeroCuatriMateriaAltaPlanDeEstudios.getText().trim().equals("  Ingrese número de cuatrimestre de la materia") ||
                anioMateriaAltaPlanDeEstudios.getText().trim().equals("  Ingrese año de la materia")) {

                mostrarDialogoCentrado(
                    "Por favor, complete todos los campos requeridos", 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Intentar parsear los valores numéricos
            try {
                numeroCuatrimestre = Integer.parseInt(numeroCuatriMateriaAltaPlanDeEstudios.getText().trim());
                anio = Integer.parseInt(anioMateriaAltaPlanDeEstudios.getText().trim());
            } catch (NumberFormatException e) {
                mostrarDialogoCentrado(
                    "El número de cuatrimestre y año deben ser números válidos", 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            boolean obligatoria = obligatoriaCheckAltaPlanDeEstudios.isSelected();
            String carreraSeleccionada = (String) seleccionarCarreraBoxAltaPlanDeEstudios.getSelectedItem();

            // Validar que se haya seleccionado una carrera
            if (carreraSeleccionada == null) {
                mostrarDialogoCentrado(
                    "Debe seleccionar una carrera", 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Obtener correlativas seleccionadas
            ArrayList<Materia> correlativas = new ArrayList<>();
            String correlativaSeleccionada = (String) seleccionarCorrelativaBoxAltaPlanDeEstudios.getSelectedItem();
            if (correlativaSeleccionada != null && !correlativaSeleccionada.equals("Ninguna")) {
                String codigoCorrelativa = correlativaSeleccionada.split(" - ")[0];
                for (Carrera carrera : gestion.getListaDeCarreras()) {
                    if (carrera.getNombreCarrera().equals(carreraSeleccionada)) {
                        for (Materia materia : carrera.getPlanDeEstudio().getListaDeMaterias()) {
                            if (materia.getCodigoMateria().equals(codigoCorrelativa)) {
                                correlativas.add(materia);
                                break;
                            }
                        }
                    }
                }
            }

            // Verificar si la materia ya existe
            boolean materiaExiste = gestion.existeMateria(codigoMateria);
            String mensaje;

            // Agregar la materia al plan de estudios de la carrera
            gestion.agregarMateriaPlanDeEstudios(codigoMateria, nombreMateria, 
                numeroCuatrimestre, anio, obligatoria, carreraSeleccionada, correlativas);

            // Mensaje según si la materia es nueva o existente
            if (materiaExiste) {
                mensaje = "Materia existente agregada al plan de estudios de " + carreraSeleccionada;
            } else {
                mensaje = "Nueva materia creada y agregada al plan de estudios de " + carreraSeleccionada;
            }

            // Mostrar mensaje de éxito
            mostrarDialogoCentrado(
                mensaje, 
                "Éxito", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Limpiar campos
            limpiarCampos();

            // Actualizar ComboBox de correlativas
            actualizarComboBoxCorrelativas();

        } catch (Exception e) {
            mostrarDialogoCentrado(
                "Error al agregar la materia: " + e.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
        // Método para mostrar diálogos centrados en la pantalla y ajustados a la izquierda
    private void mostrarDialogoCentrado(String mensaje, String titulo, int tipoMensaje) {
        JOptionPane panel = new JOptionPane(mensaje, tipoMensaje);
        panel.setOptions(new Object[] {"OK"});
        JDialog dialogo = panel.createDialog(this, titulo);
        
        // Centrar el diálogo en la pantalla
        dialogo.setLocationRelativeTo(null);
        
        // Ajustar la posición hacia la izquierda
        java.awt.Point ubicacion = dialogo.getLocation();
        dialogo.setLocation(ubicacion.x - 80, ubicacion.y); // Ajustar 80 píxeles a la izquierda
        
        dialogo.setVisible(true);
    }
    private void limpiarCampos() {
        codigoMateriaAltaPlanDeEstudios.setText("  Ingrese el código de la materia");
        nombreMateriaAltaPlanDeEstudios.setText("  Ingrese el nombre de la materia");
        numeroCuatriMateriaAltaPlanDeEstudios.setText("  Ingrese número de cuatrimestre de la materia");
        anioMateriaAltaPlanDeEstudios.setText("  Ingrese año de la materia");
        obligatoriaCheckAltaPlanDeEstudios.setSelected(false);
        optativaCheckAltaPlanDeEstudios.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton agregarMateriaBotonAltaPlanDeEstudios;
    private javax.swing.JTextField anioMateriaAltaPlanDeEstudios;
    private javax.swing.JTextField codigoMateriaAltaPlanDeEstudios;
    private javax.swing.JTextField nombreMateriaAltaPlanDeEstudios;
    private javax.swing.JTextField numeroCuatriMateriaAltaPlanDeEstudios;
    private javax.swing.JCheckBox obligatoriaCheckAltaPlanDeEstudios;
    private javax.swing.JCheckBox optativaCheckAltaPlanDeEstudios;
    private javax.swing.JPanel panelContenidoAltaPlanDeEstudios;
    private javax.swing.JComboBox<String> seleccionarCarreraBoxAltaPlanDeEstudios;
    private javax.swing.JComboBox<String> seleccionarCorrelativaBoxAltaPlanDeEstudios;
    private javax.swing.JLabel tituloIngresarDatosMateriaAltaPlanDeEstudios;
    private javax.swing.JLabel tituloPrincipalAltaPlanDeEstudios;
    private javax.swing.JLabel tituloSeleccionaCarreraAltaPlanDeEstudios;
    private javax.swing.JLabel tituloSeleccionarCorrelativaAltaPlanDeEstudios;
    // End of variables declaration//GEN-END:variables
}
