/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.views;

/**
 *
 * @author Conecta
 */
public class PanelInicio extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicio
     */
    public PanelInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenidoInicio = new javax.swing.JPanel();
        imagenUNTDF = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(644, 600));
        setPreferredSize(new java.awt.Dimension(644, 600));

        contenidoInicio.setBackground(new java.awt.Color(255, 255, 255));
        contenidoInicio.setMinimumSize(new java.awt.Dimension(644, 600));
        contenidoInicio.setPreferredSize(new java.awt.Dimension(644, 600));

        imagenUNTDF.setBackground(new java.awt.Color(201, 24, 74));
        imagenUNTDF.setFont(new java.awt.Font("Century Schoolbook", 3, 36)); // NOI18N
        imagenUNTDF.setForeground(new java.awt.Color(201, 24, 74));
        imagenUNTDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/07.png"))); // NOI18N

        javax.swing.GroupLayout contenidoInicioLayout = new javax.swing.GroupLayout(contenidoInicio);
        contenidoInicio.setLayout(contenidoInicioLayout);
        contenidoInicioLayout.setHorizontalGroup(
            contenidoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoInicioLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(imagenUNTDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(149, 149, 149))
        );
        contenidoInicioLayout.setVerticalGroup(
            contenidoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoInicioLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(imagenUNTDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(241, 241, 241))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenidoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenidoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenidoInicio;
    private javax.swing.JLabel imagenUNTDF;
    // End of variables declaration//GEN-END:variables
}
