/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.views;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.*;
/**
 *
 * @author Conecta
 */
public class PanelInscripcionMateria extends javax.swing.JPanel {
private Gestion gestion;
    /**
     * Creates new form PanelInscripcionCarrera
     */
    public PanelInscripcionMateria(Gestion gestion) {
        this.gestion = gestion;
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenidoInscribirMateria = new javax.swing.JPanel();
        tituloInscribirMateria = new javax.swing.JLabel();
        tituloSeleccionaAlumnoInscripcionMateria = new javax.swing.JLabel();
        seleccionarAlumnoBoxInscripcionMateria = new javax.swing.JComboBox<>();
        tituloSeleccionaMateriaInscripcionMateria = new javax.swing.JLabel();
        seleccionarMateriaBoxInscripcionMateria = new javax.swing.JComboBox<>();
        btnInscripcionCarrera = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(644, 600));
        setPreferredSize(new java.awt.Dimension(644, 600));

        panelContenidoInscribirMateria.setBackground(new java.awt.Color(255, 255, 255));

        tituloInscribirMateria.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        tituloInscribirMateria.setForeground(new java.awt.Color(164, 19, 60));
        tituloInscribirMateria.setText("Inscripcion de Materias");

        tituloSeleccionaAlumnoInscripcionMateria.setBackground(new java.awt.Color(255, 255, 255));
        tituloSeleccionaAlumnoInscripcionMateria.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        tituloSeleccionaAlumnoInscripcionMateria.setForeground(new java.awt.Color(255, 77, 109));
        tituloSeleccionaAlumnoInscripcionMateria.setText("Seleccionar Alumno: ");

        seleccionarAlumnoBoxInscripcionMateria.setBackground(new java.awt.Color(255, 255, 255));
        seleccionarAlumnoBoxInscripcionMateria.setForeground(new java.awt.Color(0, 0, 0));
        seleccionarAlumnoBoxInscripcionMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        seleccionarAlumnoBoxInscripcionMateria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 10, 84), 2));
        seleccionarAlumnoBoxInscripcionMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarAlumnoBoxInscripcionMateriaActionPerformed(evt);
            }
        });

        tituloSeleccionaMateriaInscripcionMateria.setBackground(new java.awt.Color(255, 255, 255));
        tituloSeleccionaMateriaInscripcionMateria.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        tituloSeleccionaMateriaInscripcionMateria.setForeground(new java.awt.Color(255, 77, 109));
        tituloSeleccionaMateriaInscripcionMateria.setText("Seleccionar Materia: ");

        seleccionarMateriaBoxInscripcionMateria.setBackground(new java.awt.Color(255, 255, 255));
        seleccionarMateriaBoxInscripcionMateria.setForeground(new java.awt.Color(0, 0, 0));
        seleccionarMateriaBoxInscripcionMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        seleccionarMateriaBoxInscripcionMateria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 10, 84), 2));
        seleccionarMateriaBoxInscripcionMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarMateriaBoxInscripcionMateriaActionPerformed(evt);
            }
        });

        btnInscripcionCarrera.setBackground(new java.awt.Color(255, 10, 84));
        btnInscripcionCarrera.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        btnInscripcionCarrera.setForeground(new java.awt.Color(255, 255, 255));
        btnInscripcionCarrera.setText("INSCRIBIR");
        btnInscripcionCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscripcionCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContenidoInscribirMateriaLayout = new javax.swing.GroupLayout(panelContenidoInscribirMateria);
        panelContenidoInscribirMateria.setLayout(panelContenidoInscribirMateriaLayout);
        panelContenidoInscribirMateriaLayout.setHorizontalGroup(
            panelContenidoInscribirMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoInscribirMateriaLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(panelContenidoInscribirMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInscripcionCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloSeleccionaMateriaInscripcionMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContenidoInscribirMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(seleccionarAlumnoBoxInscripcionMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tituloSeleccionaAlumnoInscripcionMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tituloInscribirMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seleccionarMateriaBoxInscripcionMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        panelContenidoInscribirMateriaLayout.setVerticalGroup(
            panelContenidoInscribirMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoInscribirMateriaLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(tituloInscribirMateria)
                .addGap(18, 18, 18)
                .addComponent(tituloSeleccionaAlumnoInscripcionMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionarAlumnoBoxInscripcionMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tituloSeleccionaMateriaInscripcionMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionarMateriaBoxInscripcionMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInscripcionCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(331, 331, 331))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenidoInscribirMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenidoInscribirMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void cargarDatos() {
        /// Cargar alumnos
        DefaultComboBoxModel<String> modelAlumnos = new DefaultComboBoxModel<>();
        for (Alumno alumno : gestion.getListaDeAlumnos()) {
            modelAlumnos.addElement(alumno.getLegajo() + " - " + alumno.getNombre() + " " + alumno.getApellido());
        }
        seleccionarAlumnoBoxInscripcionMateria.setModel(modelAlumnos);
        
        // Inicialmente, no cargamos materias hasta que se seleccione un alumno
        seleccionarMateriaBoxInscripcionMateria.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione un alumno primero"}));
    }
    private void actualizarMateriasDisponibles(Alumno alumno) {
        DefaultComboBoxModel<String> modelMaterias = new DefaultComboBoxModel<>();
        
        if (alumno == null || alumno.getPropuesta() == null || alumno.getPropuesta().isEmpty()) {
            modelMaterias.addElement("El alumno no está inscrito en ninguna carrera");
            seleccionarMateriaBoxInscripcionMateria.setModel(modelMaterias);
            return;
        }
        
        // Buscar la carrera del alumno
        for (Carrera carrera : gestion.getListaDeCarreras()) {
            if (carrera.getNombreCarrera().equals(alumno.getPropuesta())) {
                // Obtener materias del plan de estudio
                ArrayList<Materia> materiasCarrera = carrera.getPlanDeEstudio().getListaDeMaterias();
                ArrayList<Materia> materiasDisponibles = new ArrayList<>();
                
                System.out.println("Filtrando materias disponibles para: " + alumno.getNombre() + " " + alumno.getApellido());
                
                // Filtrar solo las materias en las que el alumno puede inscribirse
                for (Materia materia : materiasCarrera) {
                    // Verificar si el alumno ya está inscrito en la materia
                    HistoriaAcademica historia = alumno.getHistoriaAcademica();
                    EstadoMateria estadoActual = historia.buscarMateria(materia.getCodigoMateria());
                    
                    if (estadoActual != EstadoMateria.CURSANDO && estadoActual != EstadoMateria.FINALIZADA && estadoActual != EstadoMateria.PROMOCIONADA) {
                        // Verificar si cumple con los requisitos para inscribirse
                        if (carrera.getPlanDeEstudio().puedeInscribirse(alumno, materia)) {
                            materiasDisponibles.add(materia);
                            System.out.println("- Materia disponible: " + materia.getCodigoMateria() + " - " + materia.getNombreMateria());
                        }
                    }
                }
                
                // Agregar las materias disponibles al modelo
                if (materiasDisponibles.isEmpty()) {
                    modelMaterias.addElement("No hay materias disponibles para inscripción");
                } else {
                    for (Materia materia : materiasDisponibles) {
                        String infoMateria = materia.getCodigoMateria() + " - " + materia.getNombreMateria();
                        modelMaterias.addElement(infoMateria);
                    }
                }
                
                break;
            }
        }
        
        seleccionarMateriaBoxInscripcionMateria.setModel(modelMaterias);
    }
    private void seleccionarAlumnoBoxInscripcionMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarAlumnoBoxInscripcionMateriaActionPerformed
        // Obtener el alumno seleccionado y actualizar las materias disponibles
        String seleccion = (String) seleccionarAlumnoBoxInscripcionMateria.getSelectedItem();
        if (seleccion != null && !seleccion.isEmpty()) {
            try {
                // Extraer el legajo del alumno
                int legajo = Integer.parseInt(seleccion.split(" - ")[0]);
                
                // Buscar el alumno
                for (Alumno alumno : gestion.getListaDeAlumnos()) {
                    if (alumno.getLegajo() == legajo) {
                        // Actualizar materias disponibles para este alumno
                        actualizarMateriasDisponibles(alumno);
                        break;
                    }
                }
            } catch (Exception e) {
                System.out.println("Error al procesar la selección del alumno: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_seleccionarAlumnoBoxInscripcionMateriaActionPerformed

    private void seleccionarMateriaBoxInscripcionMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarMateriaBoxInscripcionMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarMateriaBoxInscripcionMateriaActionPerformed

    private void btnInscripcionCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscripcionCarreraActionPerformed
    // Validar selección de materia y alumno
    if (seleccionarMateriaBoxInscripcionMateria.getSelectedIndex() == -1) {
        mostrarDialogoCentrado("Por favor, seleccione una materia.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (seleccionarAlumnoBoxInscripcionMateria.getSelectedIndex() == -1) {
        mostrarDialogoCentrado("Por favor, seleccione un alumno.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Obtener materia y alumno seleccionados
    String materiaSeleccionada = (String) seleccionarMateriaBoxInscripcionMateria.getSelectedItem();
    String alumnoSeleccionado = (String) seleccionarAlumnoBoxInscripcionMateria.getSelectedItem();

    System.out.println("Materia seleccionada: '" + materiaSeleccionada + "'");
    System.out.println("Alumno seleccionado: '" + alumnoSeleccionado + "'");

    // Extraer el legajo del alumno
    int legajo = Integer.parseInt(alumnoSeleccionado.split(" - ")[0]);
    
    // Extraer el código de materia (la primera parte antes del guión)
    String codigoMateria = materiaSeleccionada.split(" - ")[0].trim();

    try {
        // Realizar la inscripción usando el código de la materia y capturar el resultado
        String resultado = gestion.InscripcionAlumnoMateria(legajo, codigoMateria);

        // Determinar si el resultado indica éxito o error
        if (resultado.contains("se ha inscrito correctamente")) {
            // Mostrar mensaje de éxito
            mostrarDialogoCentrado(
                resultado,
                "Inscripción Exitosa",
                JOptionPane.INFORMATION_MESSAGE);
        } else if (resultado.contains("no cumple los requisitos")) {
            // Mostrar mensaje de error de requisitos
            mostrarDialogoCentrado(
                resultado,
                "Requisitos no cumplidos",
                JOptionPane.WARNING_MESSAGE);
        } else {
            // Mostrar cualquier otro tipo de mensaje como error
            mostrarDialogoCentrado(
                resultado,
                "Error de Inscripción",
                JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        // Capturar cualquier error que ocurra durante la inscripción
        mostrarDialogoCentrado(
            "Error al inscribir al alumno: " + e.getMessage(),
            "Error de Inscripción",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace(); // Mostrar detalles en la consola para depuración
    }
    }//GEN-LAST:event_btnInscripcionCarreraActionPerformed

    // Método para mostrar diálogos centrados en la pantalla y ajustados a la izquierda
    private void mostrarDialogoCentrado(String mensaje, String titulo, int tipoMensaje) {
        JOptionPane panel = new JOptionPane(mensaje, tipoMensaje);
        panel.setOptions(new Object[] {"OK"});
        JDialog dialogo = panel.createDialog(this, titulo);
        
        // Centrar el diálogo en la pantalla
        dialogo.setLocationRelativeTo(null);
        
        // Ajustar la posición hacia la izquierda
        java.awt.Point ubicacion = dialogo.getLocation();
        dialogo.setLocation(ubicacion.x - 80, ubicacion.y); // Ajustar 80 píxeles a la izquierda
        
        dialogo.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscripcionCarrera;
    private javax.swing.JPanel panelContenidoInscribirMateria;
    private javax.swing.JComboBox<String> seleccionarAlumnoBoxInscripcionMateria;
    private javax.swing.JComboBox<String> seleccionarMateriaBoxInscripcionMateria;
    private javax.swing.JLabel tituloInscribirMateria;
    private javax.swing.JLabel tituloSeleccionaAlumnoInscripcionMateria;
    private javax.swing.JLabel tituloSeleccionaMateriaInscripcionMateria;
    // End of variables declaration//GEN-END:variables
}
