/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.views;
import java.awt.HeadlessException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import logica.*;
/**
 *
 * @author Conecta
 */
public class PanelInscripcionCarrera extends javax.swing.JPanel {
private Gestion gestion;
    /**
     * Creates new form PanelInscripcionCarrera
     */
    public PanelInscripcionCarrera(Gestion gestion) {
        this.gestion = gestion;
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenidoInscripcionCarrera = new javax.swing.JPanel();
        tituloPrincipalInscripcionCarrera = new javax.swing.JLabel();
        tituloSeleccionaCarreraInscripcionCarrera = new javax.swing.JLabel();
        seleccionarCarreraBoxInscripcionCarrera = new javax.swing.JComboBox<>();
        tituloSeleccionaAlumnoInscripcionCarrera = new javax.swing.JLabel();
        seleccionarAlumnoBoxInscripcionCarrera = new javax.swing.JComboBox<>();
        btnInscripcionCarrera = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(644, 600));

        panelContenidoInscripcionCarrera.setBackground(new java.awt.Color(255, 255, 255));

        tituloPrincipalInscripcionCarrera.setFont(new java.awt.Font("Century Gothic", 3, 30)); // NOI18N
        tituloPrincipalInscripcionCarrera.setForeground(new java.awt.Color(164, 19, 60));
        tituloPrincipalInscripcionCarrera.setText("Inscribir a un alumno a una carrera");

        tituloSeleccionaCarreraInscripcionCarrera.setBackground(new java.awt.Color(255, 255, 255));
        tituloSeleccionaCarreraInscripcionCarrera.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        tituloSeleccionaCarreraInscripcionCarrera.setForeground(new java.awt.Color(255, 77, 109));
        tituloSeleccionaCarreraInscripcionCarrera.setText("Seleccionar carrera: ");

        seleccionarCarreraBoxInscripcionCarrera.setBackground(new java.awt.Color(255, 255, 255));
        seleccionarCarreraBoxInscripcionCarrera.setForeground(new java.awt.Color(0, 0, 0));
        seleccionarCarreraBoxInscripcionCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        seleccionarCarreraBoxInscripcionCarrera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 10, 84), 2));
        seleccionarCarreraBoxInscripcionCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarCarreraBoxInscripcionCarreraActionPerformed(evt);
            }
        });

        tituloSeleccionaAlumnoInscripcionCarrera.setBackground(new java.awt.Color(255, 255, 255));
        tituloSeleccionaAlumnoInscripcionCarrera.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        tituloSeleccionaAlumnoInscripcionCarrera.setForeground(new java.awt.Color(255, 77, 109));
        tituloSeleccionaAlumnoInscripcionCarrera.setText("Seleccionar Alumno: ");

        seleccionarAlumnoBoxInscripcionCarrera.setBackground(new java.awt.Color(255, 255, 255));
        seleccionarAlumnoBoxInscripcionCarrera.setForeground(new java.awt.Color(0, 0, 0));
        seleccionarAlumnoBoxInscripcionCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        seleccionarAlumnoBoxInscripcionCarrera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 10, 84), 2));
        seleccionarAlumnoBoxInscripcionCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarAlumnoBoxInscripcionCarreraActionPerformed(evt);
            }
        });

        btnInscripcionCarrera.setBackground(new java.awt.Color(255, 10, 84));
        btnInscripcionCarrera.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        btnInscripcionCarrera.setForeground(new java.awt.Color(255, 255, 255));
        btnInscripcionCarrera.setText("INSCRIBIR");
        btnInscripcionCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscripcionCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContenidoInscripcionCarreraLayout = new javax.swing.GroupLayout(panelContenidoInscripcionCarrera);
        panelContenidoInscripcionCarrera.setLayout(panelContenidoInscripcionCarreraLayout);
        panelContenidoInscripcionCarreraLayout.setHorizontalGroup(
            panelContenidoInscripcionCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoInscripcionCarreraLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(panelContenidoInscripcionCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenidoInscripcionCarreraLayout.createSequentialGroup()
                        .addComponent(tituloSeleccionaCarreraInscripcionCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelContenidoInscripcionCarreraLayout.createSequentialGroup()
                        .addComponent(tituloPrincipalInscripcionCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(90, 90, 90))
                    .addGroup(panelContenidoInscripcionCarreraLayout.createSequentialGroup()
                        .addGroup(panelContenidoInscripcionCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(seleccionarCarreraBoxInscripcionCarrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInscripcionCarrera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seleccionarAlumnoBoxInscripcionCarrera, 0, 477, Short.MAX_VALUE)
                            .addComponent(tituloSeleccionaAlumnoInscripcionCarrera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelContenidoInscripcionCarreraLayout.setVerticalGroup(
            panelContenidoInscripcionCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoInscripcionCarreraLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(tituloPrincipalInscripcionCarrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloSeleccionaCarreraInscripcionCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionarCarreraBoxInscripcionCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloSeleccionaAlumnoInscripcionCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionarAlumnoBoxInscripcionCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInscripcionCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenidoInscripcionCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenidoInscripcionCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void cargarDatos() {
        // Cargar carreras
        DefaultComboBoxModel<String> modelCarreras = new DefaultComboBoxModel<>();
        for (Carrera carrera : gestion.getListaDeCarreras()) {
            modelCarreras.addElement(carrera.getNombreCarrera());
        }
        seleccionarCarreraBoxInscripcionCarrera.setModel(modelCarreras);

        // Cargar alumnos
        DefaultComboBoxModel<String> modelAlumnos = new DefaultComboBoxModel<>();
        for (Alumno alumno : gestion.getListaDeAlumnos()) {
            modelAlumnos.addElement(alumno.getLegajo() + " - " + alumno.getNombre() + " " + alumno.getApellido());
        }
        seleccionarAlumnoBoxInscripcionCarrera.setModel(modelAlumnos);
    }
    private void seleccionarCarreraBoxInscripcionCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarCarreraBoxInscripcionCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarCarreraBoxInscripcionCarreraActionPerformed

    private void seleccionarAlumnoBoxInscripcionCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarAlumnoBoxInscripcionCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarAlumnoBoxInscripcionCarreraActionPerformed

    private void btnInscripcionCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscripcionCarreraActionPerformed
        // Validar selección de carrera y alumno
        if (seleccionarCarreraBoxInscripcionCarrera.getSelectedIndex() == -1) {
             mostrarDialogoCentrado( "Por favor, seleccione una carrera.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (seleccionarAlumnoBoxInscripcionCarrera.getSelectedIndex() == -1) {
             mostrarDialogoCentrado("Por favor, seleccione un alumno.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtener carrera y alumno seleccionados
        String carreraSeleccionada = (String) seleccionarCarreraBoxInscripcionCarrera.getSelectedItem();
        String alumnoSeleccionado = (String) seleccionarAlumnoBoxInscripcionCarrera.getSelectedItem();

        // Extraer el legajo del alumno
        int legajo = Integer.parseInt(alumnoSeleccionado.split(" - ")[0]);

        try {
            // Realizar la inscripción
            gestion.InscripcionAlumnoCarrera(carreraSeleccionada, legajo);

            // Mostrar mensaje de éxito
             mostrarDialogoCentrado(
                "Alumno inscrito correctamente en la carrera " + carreraSeleccionada,
                "Inscripción Exitosa",
                JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException e) {
            // Mostrar cualquier error que ocurra durante la inscripción
            mostrarDialogoCentrado(
                "Error al inscribir al alumno: " + e.getMessage(),
                "Error de Inscripción",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInscripcionCarreraActionPerformed

    // Método para mostrar diálogos centrados en la pantalla y ajustados a la izquierda
    private void mostrarDialogoCentrado(String mensaje, String titulo, int tipoMensaje) {
        JOptionPane panel = new JOptionPane(mensaje, tipoMensaje);
        panel.setOptions(new Object[] {"OK"});
        JDialog dialogo = panel.createDialog(this, titulo);
        
        // Centrar el diálogo en la pantalla
        dialogo.setLocationRelativeTo(null);
        
        // Ajustar la posición hacia la izquierda
        java.awt.Point ubicacion = dialogo.getLocation();
        dialogo.setLocation(ubicacion.x - 80, ubicacion.y); // Ajustar 80 píxeles a la izquierda
        
        dialogo.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscripcionCarrera;
    private javax.swing.JPanel panelContenidoInscripcionCarrera;
    private javax.swing.JComboBox<String> seleccionarAlumnoBoxInscripcionCarrera;
    private javax.swing.JComboBox<String> seleccionarCarreraBoxInscripcionCarrera;
    private javax.swing.JLabel tituloPrincipalInscripcionCarrera;
    private javax.swing.JLabel tituloSeleccionaAlumnoInscripcionCarrera;
    private javax.swing.JLabel tituloSeleccionaCarreraInscripcionCarrera;
    // End of variables declaration//GEN-END:variables
}
