/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.views;
import logica.*;
import java.util.ArrayList;
import javax.swing.JTextArea;
/**
 *
 * @author Conecta
 */
public class PanelMaterias extends javax.swing.JPanel {
private Gestion gestion;
    /**
     * Creates new form PanelMaterias
     */
    public PanelMaterias(Gestion gestion) {
        this.gestion = gestion;
        initComponents();
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenidoMaterias = new javax.swing.JPanel();
        tituloSeleccionaCarreraPanelMateria = new javax.swing.JLabel();
        seleccionarCarreraBoxPanelMateria = new javax.swing.JComboBox<>();
        tituloSeleccionaMateriaPanelMateria = new javax.swing.JLabel();
        seleccionarMateriaBoxPanelMateria = new javax.swing.JComboBox<>();
        btnMostrarDatosCarrea = new javax.swing.JButton();
        btnMostrarAlumnosInscriptos = new javax.swing.JButton();
        scrollPanelMateria = new javax.swing.JScrollPane();

        setMinimumSize(new java.awt.Dimension(644, 600));

        panelContenidoMaterias.setBackground(new java.awt.Color(255, 255, 255));

        tituloSeleccionaCarreraPanelMateria.setBackground(new java.awt.Color(255, 255, 255));
        tituloSeleccionaCarreraPanelMateria.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        tituloSeleccionaCarreraPanelMateria.setForeground(new java.awt.Color(255, 77, 109));
        tituloSeleccionaCarreraPanelMateria.setText("Seleccionar carrera: ");

        seleccionarCarreraBoxPanelMateria.setBackground(new java.awt.Color(255, 255, 255));
        seleccionarCarreraBoxPanelMateria.setForeground(new java.awt.Color(0, 0, 0));
        seleccionarCarreraBoxPanelMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        seleccionarCarreraBoxPanelMateria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 10, 84), 2));
        seleccionarCarreraBoxPanelMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarCarreraBoxPanelMateriaActionPerformed(evt);
            }
        });

        tituloSeleccionaMateriaPanelMateria.setBackground(new java.awt.Color(255, 255, 255));
        tituloSeleccionaMateriaPanelMateria.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        tituloSeleccionaMateriaPanelMateria.setForeground(new java.awt.Color(255, 77, 109));
        tituloSeleccionaMateriaPanelMateria.setText("Seleccionar Materia: ");

        seleccionarMateriaBoxPanelMateria.setBackground(new java.awt.Color(255, 255, 255));
        seleccionarMateriaBoxPanelMateria.setForeground(new java.awt.Color(0, 0, 0));
        seleccionarMateriaBoxPanelMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        seleccionarMateriaBoxPanelMateria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 10, 84), 2));
        seleccionarMateriaBoxPanelMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarMateriaBoxPanelMateriaActionPerformed(evt);
            }
        });

        btnMostrarDatosCarrea.setBackground(new java.awt.Color(255, 10, 84));
        btnMostrarDatosCarrea.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        btnMostrarDatosCarrea.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarDatosCarrea.setText("Mostrar datos de la materia");
        btnMostrarDatosCarrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDatosCarreaActionPerformed(evt);
            }
        });

        btnMostrarAlumnosInscriptos.setBackground(new java.awt.Color(255, 10, 84));
        btnMostrarAlumnosInscriptos.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        btnMostrarAlumnosInscriptos.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarAlumnosInscriptos.setText("Mostrar alumnos inscriptos en la materia");

        scrollPanelMateria.setBackground(new java.awt.Color(153, 153, 153));
        scrollPanelMateria.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenidoMateriasLayout = new javax.swing.GroupLayout(panelContenidoMaterias);
        panelContenidoMaterias.setLayout(panelContenidoMateriasLayout);
        panelContenidoMateriasLayout.setHorizontalGroup(
            panelContenidoMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoMateriasLayout.createSequentialGroup()
                .addGroup(panelContenidoMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenidoMateriasLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(panelContenidoMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seleccionarCarreraBoxPanelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloSeleccionaCarreraPanelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloSeleccionaMateriaPanelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seleccionarMateriaBoxPanelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelContenidoMateriasLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnMostrarDatosCarrea))
                    .addGroup(panelContenidoMateriasLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnMostrarAlumnosInscriptos, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContenidoMateriasLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(scrollPanelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panelContenidoMateriasLayout.setVerticalGroup(
            panelContenidoMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoMateriasLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tituloSeleccionaCarreraPanelMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionarCarreraBoxPanelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloSeleccionaMateriaPanelMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionarMateriaBoxPanelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarDatosCarrea, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarAlumnosInscriptos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPanelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenidoMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenidoMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
   // Método para inicializar los componentes adicionales
    private void inicializarComponentes() {
        // Crear un JTextArea para mostrar la información en el JScrollPane
        JTextArea textArea = new JTextArea();
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        scrollPanelMateria.setViewportView(textArea);
        
        // Llenar el comboBox con los nombres de las carreras disponibles
        cargarCarreras();
        
        // Añadir ActionListener para el botón "Mostrar datos de la materia"
        btnMostrarDatosCarrea.addActionListener((java.awt.event.ActionEvent evt) -> {
            mostrarDatosMateria();
        });
        
        // Añadir ActionListener para el botón "Mostrar alumnos inscriptos en la materia"
        btnMostrarAlumnosInscriptos.addActionListener((java.awt.event.ActionEvent evt) -> {
            mostrarAlumnosInscriptos();
        });
        
        // Añadir un ActionListener al combo box de carreras para cargar materias
        seleccionarCarreraBoxPanelMateria.addActionListener((java.awt.event.ActionEvent evt) -> {
            cargarMaterias();
        });
    }
    
    // Método para cargar las carreras en el comboBox
    private void cargarCarreras() {
        ArrayList<Carrera> carreras = gestion.getListaDeCarreras();
        seleccionarCarreraBoxPanelMateria.removeAllItems();
        
        for (Carrera carrera : carreras) {
            seleccionarCarreraBoxPanelMateria.addItem(carrera.getNombreCarrera());
        }
    }
    
    // Método para cargar las materias en el comboBox según la carrera seleccionada
    private void cargarMaterias() {
        String nombreCarrera = (String) seleccionarCarreraBoxPanelMateria.getSelectedItem();
        if (nombreCarrera != null) {
            seleccionarMateriaBoxPanelMateria.removeAllItems();
            
            for (Carrera carrera : gestion.getListaDeCarreras()) {
                if (carrera.getNombreCarrera().equals(nombreCarrera)) {
                    for (Materia materia : carrera.getPlanDeEstudio().getListaDeMaterias()) {
                        seleccionarMateriaBoxPanelMateria.addItem(materia.getNombreMateria());
                    }
                    break;
                }
            }
        }
    }
    
 // Método para mostrar los datos de la materia seleccionada
private void mostrarDatosMateria() {
    String nombreCarrera = (String) seleccionarCarreraBoxPanelMateria.getSelectedItem();
    String nombreMateria = (String) seleccionarMateriaBoxPanelMateria.getSelectedItem();
    
    if (nombreCarrera != null && nombreMateria != null) {
        for (Carrera carrera : gestion.getListaDeCarreras()) {
            if (carrera.getNombreCarrera().equals(nombreCarrera)) {
                for (Materia materia : carrera.getPlanDeEstudio().getListaDeMaterias()) {
                    if (materia.getNombreMateria().equals(nombreMateria)) {
                        StringBuilder infoMateria = new StringBuilder();
                        infoMateria.append("Nombre de la Materia: ").append(materia.getNombreMateria()).append("\n");
                        infoMateria.append("Código de la Materia: ").append(materia.getCodigoMateria()).append("\n");
                        infoMateria.append("Es promocionable: ").append(materia.getPromocion() ? "SÍ" : "NO").append("\n");
                        infoMateria.append("Año: ").append(materia.getAnio()).append("\n");
                        infoMateria.append("Cuatrimestre: ").append(materia.getCuatrimetre()).append("\n");
                        
                        // Mostrar correlativas
                        infoMateria.append("Correlativas: ");
                        ArrayList<Materia> correlativas = materia.getCorrelativas();
                        if (correlativas != null && !correlativas.isEmpty()) {
                            infoMateria.append("\n");
                            for (Materia correlativa : correlativas) {
                                infoMateria.append("- ").append(correlativa.getNombreMateria())
                                          .append(" (").append(correlativa.getCodigoMateria()).append(")\n");
                            }
                        } else {
                            infoMateria.append("Ninguna\n");
                        }
                        
                        // Mostrar la información en el JTextArea
                        JTextArea textArea = (JTextArea) scrollPanelMateria.getViewport().getView();
                        textArea.setText(infoMateria.toString());
                        textArea.setCaretPosition(0); // Scroll al inicio
                        return;
                    }
                }
            }
        }
    }
}
    
    // Método para mostrar los alumnos inscriptos en la materia seleccionada
    private void mostrarAlumnosInscriptos() {
        String nombreCarrera = (String) seleccionarCarreraBoxPanelMateria.getSelectedItem();
        String nombreMateria = (String) seleccionarMateriaBoxPanelMateria.getSelectedItem();
        
        if (nombreCarrera != null && nombreMateria != null) {
            for (Carrera carrera : gestion.getListaDeCarreras()) {
                if (carrera.getNombreCarrera().equals(nombreCarrera)) {
                    for (Materia materia : carrera.getPlanDeEstudio().getListaDeMaterias()) {
                        if (materia.getNombreMateria().equals(nombreMateria)) {
                            StringBuilder infoAlumnos = new StringBuilder();
                            infoAlumnos.append("Nombre de la Materia: ").append(materia.getNombreMateria()).append("\n");
                            infoAlumnos.append("Alumnos Inscriptos:\n");
                            
                            boolean hayAlumnosInscriptos = false;
                            
                            // Buscar alumnos inscriptos en esta materia
                            for (Alumno alumno : carrera.getListaDeAlumnos()) {
                                HistoriaAcademica historia = alumno.getHistoriaAcademica();
                                EstadoMateria estado = historia.buscarMateria(materia.getCodigoMateria());
                                
                                if (estado == EstadoMateria.CURSANDO || estado == EstadoMateria.FINALIZADA) {
                                    infoAlumnos.append("- ").append(alumno.getNombre()).append(" ")
                                              .append(alumno.getApellido()).append(" (Legajo: ")
                                              .append(alumno.getLegajo()).append(") - Estado: ")
                                              .append(estado).append("\n");
                                    hayAlumnosInscriptos = true;
                                }
                            }
                            
                            if (!hayAlumnosInscriptos) {
                                infoAlumnos.append("- No hay alumnos inscritos en esta materia.\n");
                            }
                            
                            // Mostrar la información en el JTextArea
                            JTextArea textArea = (JTextArea) scrollPanelMateria.getViewport().getView();
                            textArea.setText(infoAlumnos.toString());
                            textArea.setCaretPosition(0); // Scroll al inicio
                            return;
                        }
                    }
                }
            }
        }
    }

    private void seleccionarCarreraBoxPanelMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarCarreraBoxPanelMateriaActionPerformed
        cargarMaterias();
    }//GEN-LAST:event_seleccionarCarreraBoxPanelMateriaActionPerformed

    private void seleccionarMateriaBoxPanelMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarMateriaBoxPanelMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarMateriaBoxPanelMateriaActionPerformed

    private void btnMostrarDatosCarreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDatosCarreaActionPerformed
        mostrarDatosMateria();
    }//GEN-LAST:event_btnMostrarDatosCarreaActionPerformed

    private void btnMostrarAlumnosInscriptosActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        mostrarAlumnosInscriptos();
    }   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarAlumnosInscriptos;
    private javax.swing.JButton btnMostrarDatosCarrea;
    private javax.swing.JPanel panelContenidoMaterias;
    private javax.swing.JScrollPane scrollPanelMateria;
    private javax.swing.JComboBox<String> seleccionarCarreraBoxPanelMateria;
    private javax.swing.JComboBox<String> seleccionarMateriaBoxPanelMateria;
    private javax.swing.JLabel tituloSeleccionaCarreraPanelMateria;
    private javax.swing.JLabel tituloSeleccionaMateriaPanelMateria;
    // End of variables declaration//GEN-END:variables
}
